name: done
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
